### ISSUE TITLE
Sound /mʃ/

### ISSUE THREAD

**Issue by XachaB** [lexibank/chindialectsurvey#6]
I am making this issue because data from this repository is considered for inclusion in lexicore.

The orthography profile has a phoneme /mʃ/. While this seems to pass CLTS validation, it is not clear to me what it is. It occurs in a single word "i mʃ ɔ". Is this a typo for /m ʃ/ ? I can not find it in https://clts.clld.org/parameters

If this is correct, when coding onto ASJP for the sound correspondence study: how should it be written ?

@LinguList @tresoldi

**Comment by LinguList** [comment]
This will be handled in the updated version of clts. But you could just
make a PR to the orthoprofile and do two segments instead ;)

**Comment by XachaB** [comment]
I find some duplicate lines in the profile. I am removing them when they are identical, but they are not always:

~~~
i̯	i̯
i̯	j
u̯	u̯
u̯	w
ˤŋ̥	ˀŋ
ˤŋ̥	ˀŋ̥
~~~

should I do something like u̯/w, i̯/j, ˤŋ̥/ˀŋ for these ?

**Comment by XachaB** [comment]
@tresoldi, do you have a suggestion for these weird duplicates  ?

**Comment by tresoldi** [comment]
Some cases look like errors, such as the `ˤŋ̥` instance that loses the voiceless diacritic.

As for the others, the slash notation seems a good solution, mapping to the glide which is what is mostly used in CLTS/BIPA, but I am speaking from a general perspective. I think @LinguList knows the dataset better?

**Comment by LinguList** [comment]
You should also have a look at the words. The u that is consonantic may also occur in a dipthong, where this makes sense. So we need to look at examples here first.

**Comment by XachaB** [comment]
Ok, I'll check these and report back, I would rather have someone else's opinion before making any final decision :)

**Comment by XachaB** [comment]
@tresoldi, I agree for ˀŋ̥. 

For the rest:

# Non syllabic i

Other existing rules for `i̯`:

~~~
ai̯     ai      A       7       thaŋhlai̯;kʰai̯hio̯;kʰrai̯kʰra;apai̯hio̯;pai̯lɛak
ei̯     ei      E       5       mei̯;tʃɛtei̯hio̯;lei̯;phamphei̯ʔ;ɛʔei̯hio̯
ii̯     ii̯/iː  I       1       krii̯hio̯
i̯      i̯      I       4       dɨi̯hio̯;lːui̯ʔ;kʰui̯juŋ;i̯j
i̯$     i̯      I       11      ui̯;tʃiʔtui̯;tɔːui̯;tui̯;tɨi̯
oi̯     oi      U       5       kroi̯aho;oʔoi̯hio̯;poi̯;hmoi̯;okoi̯
ɑi̯     ɑi      A       0       
ɔi̯     ɔi      U       7       kʰɔi̯tʃip;ɔʔɔi̯;kʰɔi̯;ɔtɔi̯;phɔi̯
ɛi̯     ɛi      E       19      ahalɛi̯hio̯;ɨhɨmɛi̯;lɨkɛi̯hio̯;mɛi̯kʰu;komthɛi̯
~~~

Contexts not covered by other rules for `i̯`:

~~~
20329   HyowKongtuBoroKukyachariinRajasthali-A  blood   tui̯hlɔʔ
16936   HyowLaituGhungurumukParainBandarban-A   guᵐs    dɨi̯hio̯
24081   HyowKongtuBoroKukyachariinRajasthali-A  sleeping area   ulːui̯ʔ
24082   HyowLaituGhungurumukParainBandarban-A   sleeping area   lːui̯ʔ
3408    HyowKongtuBoroKukyachariinRajasthali-A  soil (earth)    kʰui̯juŋ
3409    HyowLaituGhungurumukParainBandarban-A   soil (earth)    kʰui̯juŋ
32774   HyowKongtuBoroKukyachariinRajasthali-A  to scratch (self)       ɨi̯kʰɨl
28354   HyowKongtuBoroKukyachariinRajasthali-A  to swallow      ɨi̯kʰɨlːa
11908   HyowLaituGhungurumukParainBandarban-A   wing    i̯j
~~~


There are three different contexts. In the spirit of existing rules, I think we can write the two firsts "i" in diphthongs:

~~~
ui̯     ui
ɨi̯     ɨi
~~~


The last case is `i̯j` and is less obvious: what would be a non syllabic i followed by j ?



Moreover, I have a doubt on the validity of the final rule:

~~~
i̯$     i̯      I       11      ui̯;tʃiʔtui̯;tɔːui̯;tui̯;tɨi̯
~~~

All are in diphthongs which are addressed by existing rules, here is an example for each:

~~~
17550   HyowKongtuBoroKukyachariinRajasthali-A  back    ɔʔɔi̯
6795    HyowKongtuBoroKukyachariinRajasthali-A  banana  ui̯
19562   HyowKongtuBoroKukyachariinRajasthali-A  bone    ɨʃɨi̯
4498    HyowKongtuBoroKukyachariinRajasthali-A  cave    thaŋhlai̯
17037   HyowKongtuBoroKukyachariinRajasthali-A  chin    ahalɛi̯
26848   HyowKongtuBoroKukyachariinRajasthali-A  gongs   ɔpɔi̯
15561   HyowKongtuBoroKukyachariinRajasthali-A  hair (body)     mei̯
~~~

I think the final non syllabic i rule should be removed.


# Non syllabic u

Other rules for non syllabic u:

~~~
au̯     au      A       0       
eu̯     eu      E       0       
ou̯     ou      U       5       oʔou̯k kʰo;tʃou̯ŋho;oŋou̯uhuo̯;hou̯huo̯;abou̯k
u̯      u̯      Y       4       kʰɔhiu̯ŋ;ou̯ktʃuk;ɔu̯n;iu̯ŋ
u̯$     u̯      Y       3       hiu̯;ɔbɔnkiu̯;thu̯
ɑu̯     ɑu      A       0       
ɔu̯     ɔu      U       7       kʰɔlɔu̯;ɔthɔu̯;kʰɔu̯tʃo;nɔu̯lɛktʃɔ;lɔu̯ŋ
ɛu̯     ɛu      E       0       
~~~

Contexts not covered by other rules for `u̯` are all `iu̯`:

~~~
553     HyowKongtuBoroKukyachariinRajasthali-A  cloud   kʰɔhiu̯ŋ
554     HyowLaituGhungurumukParainBandarban-A   cloud   kʰɔhiu̯ŋ
3866    HyowKongtuBoroKukyachariinRajasthali-A  sand    uiu̯ŋkuŋ
3867    HyowLaituGhungurumukParainBandarban-A   sand    iu̯ŋ
2667    HyowKongtuBoroKukyachariinRajasthali-A  to be hot (person)      kiu̯p
~~~

So I suggest to replace in the spirit of the  existing ones, by: 

~~~
iu̯     iu
~~~

Again, I think the final rule might be wrong because there are three contexts, two of which are already covered by diphthong rules (`iu̯` and `ɔu̯`):

~~~
11249   HyowKongtuBoroKukyachariinRajasthali-A  tail    ɔbɔnkiu̯
12161   HyowKongtuBoroKukyachariinRajasthali-A  to fly  thɔu̯
12162   HyowLaituGhungurumukParainBandarban-A   to fly  thu̯
~~~

The third one, `hu̯`, has a single occurence, and I do not know how it should be transcribed.


# Other non syllabic vowels kept as is

In fact, I think any lines in the profile where the non syllabic vowel is kept as is are mistakes:

Here are all the other ones:

~~~
a̯      a̯      A       1       moa̯m
a̯$     a̯      A       1        hlomhloa̯
o̯      o̯      U       0
o̯$     o̯      U       0
ɪ̯      ɪ̯      I       4        ʃeɪ̯hio̯;ebeɪ̯ŋ;deɪ̯k;hatheɪ̯ʔ
~~~

The o ones can just be removed, they never happen. for `a̯`, the other rules are:


# Non syllabic a

~~~
ia̯     j a     J A     2       phia̯;pilːia̯ŋa
ua̯     w a     W A     0 
~~~

And the contexts outside of these rules are only these two occurences, both of `oa̯`:


~~~
24391   HyowLaituGhungurumukParainBandarban-A   blanket hlomhloa̯
27351   HyowLaituGhungurumukParainBandarban-A   knife   moa̯m
~~~

So I think the two rules should be removed and replaced by a single specific rule. Would this work ?

~~~
oa̯     oa 
~~~

## Non syllabic `ɪ̯`

There are no other rules with `ɪ̯`, and all the occurences are:

~~~
19563   HyowLaituGhungurumukParainBandarban-A   bone    ʃeɪ̯hio̯
10099   HyowKongtuBoroKukyachariinRajasthali-A  rat     ebeɪ̯ŋ
10100   HyowLaituGhungurumukParainBandarban-A   rat     ebeɪ̯ŋ
4170    HyowLaituGhungurumukParainBandarban-A   silver  theɪ̯
5040    HyowKongtuBoroKukyachariinRajasthali-A  thorn   ŋɔŋtheɪ̯
5041    HyowLaituGhungurumukParainBandarban-A   thorn   ŋɔŋtheɪ̯
2545    HyowKongtuBoroKukyachariinRajasthali-A  to be hot (water)       deɪ̯k
2546    HyowLaituGhungurumukParainBandarban-A   to be hot (water)       deɪ̯k
10437   HyowKongtuBoroKukyachariinRajasthali-A  to bite eleɪ̯
29460   HyowLaituGhungurumukParainBandarban-A   to yarwn        hatheɪ̯ʔ
~~~

Where the relevant contexts are all `eɪ̯`. I think we can replace the current rule and instead make a rule:

~~~
eɪ̯    eɪ
~~~


# Summary of proposition

Here are the changes I am suggesting. The notation I picked for diphthongs (using two plain vowels) is simply for coherence with the rest of the profile and existing rules:

~~~
-i̯	i̯
-i̯	j
+ui̯	ui
+ɨi̯	ɨi
+i̯j	# to be decided

-u̯	u̯
-u̯$	u̯
+iu̯	iu
+hu̯	# to be decided

-a̯	a̯
-a̯$	a̯
+oa̯	oa

-ɪ̯	ɪ̯
+eɪ̯	eɪ
~~~

I intend to remove all rules which have frequency 0, they clutter the profile.
I have the impression that the profile is still a little bit rough and would benefit from a careful look at everything (not just non syllabic vowels).

**Comment by tresoldi** [comment]
@XachaB , your solution sounds very sensible and consistent to me.

As for `+i̯j`, I suppose that, if you are going to keep a single rule, it should be mapped to just `i j`. The parser will interpret "ii" as a long vowel, not a diphthong.

As for `hu̯` (in "thu̯"), given it is a single entry I would probably map the entire string (`^thu̯$`) to `tʰ u`. However, if you check the sources, the value is `thu̯`, so it is probably an analogue case to the one above: `u w`.

**Comment by XachaB** [comment]
Do you mean it is: "�th�u̯" -> "th u w" ?

**Comment by LinguList** [comment]
I'll handle this today, it is important to keep a certain syllable structure for those langauges.

**Comment by XachaB** [comment]
Ok, if you prefer to do it yourself. If your plate is full, I did not mind doing it, and had started working on it already.

**Comment by LinguList** [comment]
The problem is that I think that there are errors in the coding, as they propose unlikely sound sequences, due to the non-syllabic marker being placed on the wrong sounds. As a result, I'd propose a rather strict re-mapping of these cases, where iu becomes `j u`, etc. Let me check first, before we make a decision here.

**Comment by LinguList** [comment]
|   no | morpheme   | value                                                | form                 | tokens                                  |
|-----:|:-----------|:-----------------------------------------------------|:---------------------|:----------------------------------------|
|    1 | ʔ          | ʔ.pei                                                | ʔ.pei                | ʔ + p ei                                |
|    2 | p          | p.pɔi                                                | p.pɔi                | p + p ɔi                                |
|    3 | p u i      | pui.dɔ                                               | pui.dɔ               | p u i + d ɔ                             |
|    4 | p ə i ʔ    | pə.pəiʔ                                              | pə.pəiʔ              | p ə + p ə i ʔ                           |
|    5 | ŋ          | ʔɑ ŋ.ɗən                                             | ʔɑ ŋ.ɗən             | ʔ ɑ + ŋ + ɗ ə n                         |
|    6 | kʰ ə i     | ʔɑ kʰəi                                              | ʔɑ kʰəi              | ʔ ɑ + kʰ ə i                            |
|    7 | kʰ ɔ l ɔu  | kʰɔlɔu̯                                               | kʰɔlɔu̯               | kʰ ɔ l ɔu                               |
|    8 | t ə u      | təu.jɔŋ.təu.ʃɔ (W)                                   | təu.jɔŋ.təu.ʃɔ       | t ə u + j ɔ ŋ + t ə u + ʃ ɔ             |
|    9 | k          | ʔɑ k.Xɨŋ k.sʰe                                       | ʔɑ k.Xɨŋ k.sʰe       | ʔ ɑ + k + χ ɨ ŋ + k + sʰ e              |
|   10 | kʰ x ɨ k   | k.kʰxɨk k.sʰe                                        | k.kʰxɨk k.sʰe        | k + kʰ x ɨ k + k + sʰ e                 |
|   11 | m          | m.ɬiŋ                                                | m.ɬiŋ                | m + ɬ i ŋ                               |
|   12 | b          | b.liŋ                                                | b.liŋ                | b + l i ŋ                               |
|   13 | i m i ŋ    | imiŋ                                                 | imiŋ                 | i m i ŋ                                 |
|   14 | h i ə r    | liŋ.hiər                                             | liŋ.hiər             | l i ŋ + h i ə r                         |
|   15 | m u i      | kʰɑŋ.mui                                             | kʰɑŋ.mui             | kʰ ɑ ŋ + m u i                          |
|   16 | g ʷ/w ɑ t  | iŋ.ɡʷɑt                                              | iŋ.ɡʷɑt              | i ŋ + g ʷ/w ɑ t                         |
|   17 | n          | ʔim/n.kɑl                                            | n.kɑl                | n + k ɑ l                               |
|   18 | kʰ u i     | kɑi.kʰui                                             | kɑi.kʰui             | k ɑi + kʰ u i                           |
|   19 | i ʔ i p    | iʔip pho                                             | iʔip pho             | i ʔ i p + pʰ o                          |
|   20 | tʰ         | tʰ.vɑi                                               | tʰ.vɑi               | tʰ + v ɑi                               |
|   21 | ɓ ɨ i      | pɑ.lɑ/ɓɨi (plain)                                    | ɓɨi                  | ɓ ɨ i                                   |
|   22 | k i u      | kut.kiu                                              | kut.kiu              | k u t + k i u                           |
|   23 | h m u      | tɑ.hmu                                               | tɑ.hmu               | t ɑ + h m u                             |
|   24 | h u i      | huŋ.hui                                              | huŋ.hui              | h u ŋ + h u i                           |
|   25 | l̥ i ŋ +    | mɑ.hliŋ.                                             | mɑ.hliŋ.             | m ɑ + l̥ i ŋ +                           |
|   26 | kʰ x u k   | m.kʰxuk.pɑŋ                                          | m.kʰxuk.pɑŋ          | m + kʰ x u k + p ɑ ŋ                    |
|   27 | h ŋ u      | hŋu.lum                                              | hŋu.lum              | h ŋ u + l u m                           |
|   28 | h n ɔ      | hnɔ.tʰɑi                                             | hnɔ.tʰɑi             | h n ɔ + tʰ ɑi                           |
|   29 | h n u      | hnu.tʰɑi                                             | hnu.tʰɑi             | h n u + tʰ ɑi                           |
|   30 | u i̯        | ui̯                                                   | ui̯                   | u i̯                                     |
|   31 | h ŋ ɑ m    | hŋɑm.pu.tʰeʔ                                         | hŋɑm.pu.tʰeʔ         | h ŋ ɑ m + p u + tʰ e ʔ                  |
|   32 | n̥ a ⁿp u   | n̥ɔ.tʰɛʔ/ n̥aᵐpu tʰiŋ (tree)                           | n̥aᵐpu tʰiŋ           | n̥ a ⁿp u + tʰ i ŋ                       |
|   33 | l u k i    | luki                                                 | luki                 | l u k i                                 |
|   34 | sʰ         | sʰ/ʃɑ k.kʰi                                          | sʰ                   | sʰ                                      |
|   35 | h ʷ/w ɔ ŋ  | ʔɑ.hʷɔŋ                                              | ʔɑ.hʷɔŋ              | ʔ ɑ + h ʷ/w ɔ ŋ                         |
|   36 | m̥ u i      | muŋ.m̥ui                                              | muŋ.m̥ui              | m u ŋ + m̥ u i                           |
|   37 | h m ɯ      | kʰo.hmɯ                                              | kʰo.hmɯ              | kʰ o + h m ɯ                            |
|   38 | h m u i    | kʰo.hmui                                             | kʰo.hmui             | kʰ o + h m u i                          |
|   39 | h m ɯ n    | kʰu.hmɯn                                             | kʰu.hmɯn             | kʰ u + h m ɯ n                          |
|   40 | o ʔ ou k   | oʔou̯k kʰo                                            | oʔou̯k kʰo            | o ʔ ou k + kʰ o                         |
|   41 | h ŋ w ɑ    | kʰɔ.hŋuɑ                                             | kʰɔ.hŋuɑ             | kʰ ɔ + h ŋ w ɑ                          |
|   42 | m ɨ i      | kʰɑ.mɨi                                              | kʰɑ.mɨi              | kʰ ɑ + m ɨ i                            |
|   43 | kʰ ə u     | kʰɑ.kʰəu mul                                         | kʰɑ.kʰəu mul         | kʰ ɑ + kʰ ə u + m u l                   |
|   44 | ɓ ə i      | m.kʰɑ.ɓəi m̥u                                         | m.kʰɑ.ɓəi m̥u         | m + kʰ ɑ + ɓ ə i + m̥ u                  |
|   45 | kʰ u ɛ     | kʰuɛ                                                 | kʰuɛ                 | kʰ u ɛ                                  |
|   46 | p u ɛ      | puk.puɛ                                              | puk.puɛ              | p u k + p u ɛ                           |
|   47 | z u i      | juŋ.zui                                              | juŋ.zui              | j u ŋ + z u i                           |
|   48 | t u i      | mɑ.kə.tui                                            | mɑ.kə.tui            | m ɑ + k ə + t u i                       |
|   49 | ʃ ɔ k i    | ʃɔki                                                 | ʃɔki                 | ʃ ɔ k i                                 |
|   50 | + tʃ u     | (m).tʃu                                              | .tʃu                 | + tʃ u                                  |

**Comment by LinguList** [comment]
I'll take over, since there's more to it then just modifying some sounds. I found 600 elements which I cannot explain with a basic syllable model for SEA languages.

**Comment by XachaB** [comment]
Ok, good luck with this !

**Comment by LinguList** [comment]
Thsi is computed with the help of github.com/lingpy/linse, where we have a function called "seallable", which allows me to check if a syllable conforms to our expectations. This is obviously not working well here. We find as many as 600 cases in which the syllable is NOT conforming. The table above is just an example of the first 50 elements.

**Comment by LinguList** [comment]
Even more annoying is that there's an `\x84` that is occuring in some entries, which should also be deleted.
